language: node_js
sudo: false
node_js:
  - 0.10
before_install:
  - npm install -g grunt-cli
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - grunt start > /dev/null &
script:
  - grunt eslint
  - grunt karma:travis
  - grunt coverage
  - grunt e2e-build
after_success:
  - bash <(curl -s https://codecov.io/bash)
